"""ID3 tag fallback: derive title and artist from filename.

Many DJ remix files carry blank or whitespace-only ID3 tags but encode useful
metadata in the filename itself.  This module parses those filenames so the
AVRCP bridge (and the Stream Deck browser) can display something meaningful
on the Camry head unit instead of "(Unknown) / (Unknown)".

Recognised filename patterns
-----------------------------

Key/tempo prefix (generated by Mixed In Key, Rekordbox, Serato, etc.):
    ``6A - 138 - Song Name - Artist``
    ``6A_ Song Name - Artist``
    ``6A – 138 – Song Name``

N-in-1 remix prefix:
    ``3 IN 1 - Song Name``
    ``3IN1 - Song Name``
    ``2in1 - Song Name``

After stripping those prefixes the remainder is split on the LAST occurrence
of ``  `` (space-hyphen-space) to give Title and Artist.  A bare hyphen
without surrounding spaces (e.g. ``NAMY-1``) is treated as part of the word,
not a separator, so artist tags like ``NAMY-1`` stay intact.

If no `` - `` separator is found, the whole remainder is used as the title and
the artist is returned as an empty string (blank is always better than
"(Unknown)" on the Camry display).
"""
from __future__ import annotations

import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Regex patterns — compiled once at import time
# ---------------------------------------------------------------------------

# Key/tempo prefix variants:
#   "6A - 138 - "   "6A_ "   "12A - 138 - "   "6Ab - 138 - "
_KEY_TEMPO_RE = re.compile(
    r"^\d{1,2}[A-Ga-g][b#]?"   # key number + letter + optional flat/sharp
    r"(?:\s*[-_]\s*\d{2,3})?"  # optional "- 138" tempo part
    r"\s*[-_]\s*",              # separator before the real content
    re.ASCII,
)

# N-in-1 prefix variants: "3 IN 1 - ", "3IN1 - ", "2in1 - "
_N_IN_1_RE = re.compile(
    r"^\d+\s*IN\s*\d+\s*-\s*",
    re.IGNORECASE | re.ASCII,
)

# Separator: space - space (the only reliable title/artist divider)
_SEP = " - "


def parse(filename: str) -> tuple[str, str]:
    """Parse ``filename`` (with or without extension) into ``(title, artist)``.

    Returns ``("", "")`` for empty input.  The artist may be an empty string
    when no `` - `` separator is found — callers should treat ``""`` as "no
    artist tag" and NOT forward it to devices as "(Unknown)".

    Examples::

        >>> parse("6A - 138 - HAC GIAY 2025 - HD.mp3")
        ('HAC GIAY 2025', 'HD')
        >>> parse("ANG MAY VO TINH - THANH SUN.mp3")
        ('ANG MAY VO TINH', 'THANH SUN')
        >>> parse("8A - 140 - REAL LOVE X LOWK FT ELSOQ.mp3")
        ('REAL LOVE X LOWK FT ELSOQ', '')
        >>> parse("3 IN 1 - BANH MI 2026 HD_2.mp3")
        ('BANH MI 2026 HD_2', '')
        >>> parse("6A_ Ke$ha - Crazy Kids.wav")
        ('Ke$ha', 'Crazy Kids')
    """
    stem = Path(filename).stem.strip()
    if not stem:
        return "", ""

    # Strip N-in-1 prefix first (it can precede the key/tempo prefix too)
    stem = _N_IN_1_RE.sub("", stem).strip()
    # Strip key/tempo prefix
    stem = _KEY_TEMPO_RE.sub("", stem).strip()

    if not stem:
        return "", ""

    # Split on LAST " - " to separate title from artist.
    # Using rfind so "Title Part 1 - Title Part 2 - Artist" → ("Title Part 1 - Title Part 2", "Artist")
    idx = stem.rfind(_SEP)
    if idx == -1:
        return stem, ""

    title = stem[:idx].strip()
    artist = stem[idx + len(_SEP):].strip()
    return title or stem, artist


# ---------------------------------------------------------------------------
# Spam / watermark detection
# ---------------------------------------------------------------------------

# Artist tags that are promotional watermarks rather than real artist names.
# Common pattern in Vietnamese DJ files: the distributor embeds their contact
# info (Zalo, phone numbers, promo text) into the artist field.
_SPAM_RE = re.compile(
    r"ZALO\s*:"           # Zalo contact handle
    r"|(?:^|[\s/])0\d{8,10}(?:$|[\s/])"  # Vietnamese phone numbers
    r"|\bDEMO\s+X[IĨ]N\b"  # "DEMO XỊN" (common promo phrase)
    r"|\bLOGO\s*&",         # "LOGO & POSTER" promo line
    re.IGNORECASE,
)

# Also treat very long tags (> 80 chars) that contain multiple slashes as spam.
_SPAM_SLASH_LEN = 60  # if tag has a slash AND is this long, it's promo


def _is_spam(tag: str) -> bool:
    """Return True if ``tag`` looks like a promotional watermark."""
    if _SPAM_RE.search(tag):
        return True
    if len(tag) > _SPAM_SLASH_LEN and "/" in tag:
        return True
    return False


def enrich(title: str, artist: str, filename: str) -> tuple[str, str]:
    """Return ``(title, artist)`` using the ID3 values when non-blank and not
    spam, falling back to filename parsing otherwise.

    A tag is considered blank if it is empty or contains only whitespace.
    A tag is considered spam if it contains promotional watermark content
    (Zalo handles, phone numbers, promo phrases) — these are stripped and
    replaced with the filename-parsed value.

    Returns ``(title, "")`` rather than ``(title, "(Unknown)")`` when no artist
    can be determined: an empty string is what the Camry and Bose headphones
    display as "nothing" rather than "(Unknown)".
    """
    clean_title = (title or "").strip()
    clean_artist = (artist or "").strip()

    # Strip spam watermarks — treat them the same as blank
    if _is_spam(clean_title):
        clean_title = ""
    if _is_spam(clean_artist):
        clean_artist = ""

    if clean_title and clean_artist:
        return clean_title, clean_artist

    parsed_title, parsed_artist = parse(filename)

    return (
        clean_title or parsed_title,
        clean_artist or parsed_artist,
    )
